### ISSUE TITLE
Delete: CAC logo.png and paste/upload image directly on Readme.md

### ISSUE THREAD

**Issue by KukretiShubham** [cac-nitj/digital-assets#2]
Delete CAC logo.png and paste/upload cac logo.png on Readme.md

**Comment by PuneetDabral** [comment]
sir can i?

**Comment by KukretiShubham** [comment]
@PuneetDabral sure, go aheah.

**Comment by PuneetDabral** [comment]
sir i think i made a mistake ...?

**Comment by KukretiShubham** [comment]
You can download the logo & while editing Readme, drag and drop the logo.

**Comment by PuneetDabral** [comment]
ok bro i will again send a pr....

**Comment by KukretiShubham** [comment]
@PuneetDabral are you from NITJ?

**Comment by PuneetDabral** [comment]
no bro i am from chitkara university ...

**Comment by KukretiShubham** [comment]
Ohk. Good work.

**Comment by PuneetDabral** [comment]
are you from?

**Comment by KukretiShubham** [comment]
I am from NITJ. This community is also NITJ based. But we are promoting OpenSource culture. So, everyone is allowed to contribute.

**Comment by PuneetDabral** [comment]
ohh nice how can i join this community?

**Comment by KukretiShubham** [comment]
create an issue [here](https://github.com/cac-nitj/support/issues/new?assignees=&labels=github-invitation&template=invitaiton.yml&title=Please+invite+me+to+the+community). You will get invitation.
